### PR TITLE
Provide psm_get_ipivect even on single CPU systems

### PR DESCRIPTION
**Pull request by gwr**
This is what I'm testing on my system.  No full build yet, so just dropping in a new "unix" in an existing r151030 build for now.  I'll open another PR against master once this tests out OK.

https://github.com/omniosorg/illumos-omnios/issues/482

### CODE REVIEW

**Comment by danmcd** [comment]
My Azure VM shows "pcplusmp".  I suspect Hyper-V vers. 1 is also pcplusmp.  Maybe v2 is apix?

**Comment by gwr** [comment]
Ugh. My testing is stuck.  I'm having trouble with the network configuration on my Hyper-V machine. ("stock" install)
Even the legacy dnet doesn't work for me at the moment.  I must have messed up something.

**Comment by danmcd** [comment]
I *might* be able to test this tonight.  BRB with an update.

**Comment by danmcd** [comment]
Test BE on Azure isn't looking good in the does-it-still-boot-on-2-CPUs case.  Not sure why, it goes into failing to reach single-user-mode, never mind login.

```
WARNING: sd:sd_io_time is set more than once in //etc/system. "set sd:sd_io_time = 300" applie
d as the current setting.

SunOS Release 5.11 Version io-030 64-bit
Copyright (c) 1983, 2010, Oracle and/or its affiliates. All rights reserved.
Copyright (c) 2017-2019 OmniOS Community Edition (OmniOSce) Association.
WARNING: /pci@0,0/pci-ide@7,1/ide@0 unable to enable write cache targ=0
WARNING: /pci@0,0/pci-ide@7,1/ide@0 unable to enable write cache targ=1
Requesting System Maintenance Mode
(See /lib/svc/share/README for more information.)
svc:/system/early-manifest-import:default exited with status 1

Enter user name for system maintenance (control-d to bypass): root
Enter root password (control-d to bypass):
single-user privilege assigned to root on /dev/console.
Entering System Maintenance Mode

Jun  4 02:23:12 su: 'su root' succeeded for root on /dev/console
Requesting System Maintenance Mode
(See /lib/svc/share/README for more information.)
svc:/system/early-manifest-import:default exited with status 1

Enter user name for system maintenance (control-d to bypass): Requesting System Maintenance Mo
de
(See /lib/svc/share/README for more information.)
svc:/system/early-manifest-import:default exited with status 1

Enter user name for system maintenance (control-d to bypass):
```

**Comment by danmcd** [comment]
It COULD have been the way I modified my other BE.  I'm not able to test further, i.e. with a full and proper build of 030+this-fix, until later this week.  Tomorrow is pre-shot already.  :)

**Comment by citrus-it** [comment]
If this works, we also need to drop these two lines in vmbus:

https://github.com/omniosorg/illumos-omnios/blob/master/usr/src/uts/intel/io/hyperv/vmbus/vmbus.c#L843

I'll build a test installer ISO to check under hyper-v.

**Comment by citrus-it** [comment]
Also this:

```diff
--- a/usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
+++ b/usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
@@ -841,7 +841,7 @@ vmbus_intr_setup(struct vmbus_softc *sc)
        }

        if (psm_get_ipivect == NULL)
-               return (0);
+               panic("Hyper-V vmbus cannot get IDT vector (no PSM support)");

        sc->vmbus_idtvec = psm_get_ipivect(IPL_VMBUS, -1);
        if (add_avintr(NULL, IPL_VMBUS, (avfunc)vmbus_handle_intr,
```

**Comment by gwr** [comment]
I'm still stuck on testing (until I get time to figure out why networking is broken on my hyper-v server).
Meanwhile, it occurred to me that the vmbus driver should really fail to attach when psm_get_ipivect is not provided by the platform module (i.e. test that in vmbus_attach and error out if NULL).
The module cannot work correctly without an interrupt.

**Comment by gwr** [comment]
I pushed a change to do as described above (fix vmbus_attach).
Fixes: Panic if Hyper-V cannot create interrupt handler #484
Sorry I still can't test this...

**Comment by citrus-it** [comment]
I'm afraid this isn't working. If I boot a single CPU machine under hyper-v, it hangs. There are two threads running in vmbus, one waiting for a condition variable to say that the bus scan is complete, and the other in a loop waiting for something that doesn't arrive.

I think we have got past the interrupt handler setup now and are hitting something else.

```
hv_vmbus0: vmbus_initchild parent fffffe01e5a55808 child fffffe01e5a3a2a8 (a9a0f4e7-5a45-4d96-b827-8a841e8c03e6 : 242ff919-07db-4180-9c2e-b86cb68c8c55)
WARNING: hv_kvp0: chan10 update cpu0 flag_cnt to 1

NMI received: entering kmdb

Loaded modules: [ scsi_vhci stmf_sbd mac uppc neti zfs s1394 apix uhci hook lofs ip usba xhci specfs pcplusmp mm cpu.generic arp stmf sockfs ]
kmdb: target stopped at:
kmdb_enter+0xb: movq   %rax,%rdi
[0]> ::interrupts
IRQ  Vect IPL Bus    Trg Type   CPU Share APIC/INT# ISR(s)
1    0x41 5   ISA    Edg Fixed  0   1     0x0/0x1   i8042`i8042_intr
4    0xb0 12  ISA    Edg Fixed  0   1     0x0/0x4   asy`asyintr
9    0x81 9   PCI    Lvl Fixed  0   1     0x0/0x9   acpica`acpi_wrapper_isr
12   0x42 5   ISA    Edg Fixed  0   1     0x0/0xc   i8042`i8042_intr
14   0x40 5   ISA    Edg Fixed  0   1     0x0/0xe   ata`ata_intr
32   0x20 2          Edg IPI    all 1     -         cmi_cmci_trap
33   0x21 1          Edg IPI    all 1     -         hv_vmbus`vmbus_handle_intr
160  0xa0 0          Edg IPI    all 0     -         pir_ipi
208  0xd0 14         Edg IPI    all 1     -         kcpc_hw_overflow_intr
209  0xd1 14         Edg IPI    all 1     -         cbe_fire
210  0xd3 14         Edg IPI    all 1     -         cbe_fire
240  0xe0 15         Edg IPI    all 1     -         pcplusmp`apic_error_intr
[0]>
[0]> ::stacks -m hv_vmbus
THREAD           STATE    SOBJ                COUNT
fffffe01e92f0100 SLEEP    CV                      1
                 swtch+0x141
                 cv_wait+0x70
                 hv_vmbus`vmbus_scan+0x9f
                 hv_vmbus`vmbus_doattach+0x137
                 hv_vmbus`vmbus_attach+0x9a
                 devi_attach+0x92
                 attach_node+0xa7
                 i_ndi_config_node+0x7d
                 i_ddi_attachchild+0x48
                 devi_attach_node+0x5e
                 devi_config_one+0x294
                 ndi_devi_config_one+0xa8
                 resolve_pathname+0x155
                 e_ddi_hold_devi_by_path+0x1d
                 hold_devi+0x143
                 ddi_hold_devi_by_instance+0x19
                 softmac`softmac_hold_device+0xa8
                 stubs_common_code+0x59
                 dld`drv_ioc_phys_attr+0x85
                 dld`drv_ioctl+0x1e4
                 cdev_ioctl+0x39
                 specfs`spec_ioctl+0x60
                 fop_ioctl+0x55
                 ioctl+0x9b
                 sys_syscall32+0x12f

fffffe0003d83c20 ONPROC   <NONE>                  1
                 tsc_read+3
                 gethrtime+0xa
                 drv_usecwait+0x47
                 hv_vmbus`vmbus_chan_open_br+0x2da
                 hv_vmbus`vmbus_chan_open+0xeb
                 hv_vmbus`vmbus_ic_attach+0x77
                 hv_kvp`hv_kvp_attach+0x12c
                 devi_attach+0x92
                 attach_node+0xa7
                 i_ndi_config_node+0x7d
                 i_ddi_attachchild+0x48
                 devi_attach_node+0x5e
                 ndi_devi_online+0x9a
                 hv_vmbus`vmbus_add_child+0x110
                 hv_vmbus`vmbus_prichan_attach_task+0x11
                 taskq_thread+0x2d0
                 thread_start+8
```

**Comment by citrus-it** [comment]
This change resolves this second issue - https://github.com/omniosorg/illumos-omnios/pull/490
In conjunction with the commits here, we can now boot single CPU!

```
Last login: Tue Jun  4 23:08:1 2019 on consol
Jun  4 23:09:34 omniosce login ROOT LOGIN /de/console
OmniOS 5.11     omnios-r15103013ff342c49      June 2019
root@omniosce:~# psrinfo -v
Status of virtual processor 0 s of: 06/04/2019 23:09:38
  on-line since 06/04/2019 23:09:22.
  The i386 processor operates at 4000 MHz,
        and has an i387 compatible floating point processor.
root@omniosce:~# uname -a
SunOS omniosce 5.11 omnios-r15030-13ff342c49 86pc i386 i86pc
```

**Comment by citrus-it** [comment]
@danmcd - can you find time to test this second patch on Azure?

@gwr - can you please re-base the commits here on master? We can get them merged and then cherry pick them back to r151030.

**Comment by gwr** [comment]
Squashed the my two commits and rebased onto master.
Nice work figuring out #490

**Comment by gwr** [comment]
That makes sense. Thanks.  I pushed the pre-squash version of this to my omnios-482 branch in case that's still of any use.

**Comment by gwr** [comment]
I verified this works on Hyper-V in Windows Server 2012 R2.

**Pull request merged**
