### PR TITLE
16524 driver for 38xx HBA in illumos (r151046)

### PR DESCRIPTION
**Pull request by danmcd**
Reviewed by: Dan McDonald <danmcd@mnx.io>
Reviewed by: Hans Rosenfeld <rosenfeld@grumpf.hope-2000.org>
Reviewed by: Bill Sommerfeld <sommerfeld@hamachi.org>
Reviewed by: Dale Ghent <daleg@elemental.org>
Approved by: Robert Mustacchi <rm@fingolfin.org>

### CODE REVIEW

**Comment by danmcd** [comment]
Cherry pick apparently worked better than expected.  Gonna try and build it now.

**Comment by danmcd** [comment]
Should address #1482

**Review by citrus-it — APPROVED** [review]

**Comment by citrus-it** [comment]
Thanks for doing this Dan - I test built it on an r151046 VM and got a clean mail_msg:

```

==== Nightly distributed build started:   Wed Jun  5 16:16:30 UTC 2024 ====
==== Nightly distributed build completed: Wed Jun  5 17:22:19 UTC 2024 ====

==== Total build time ====

real    1:05:48

==== Build environment ====

/usr/bin/uname
SunOS r151046 5.11 omnios-r151046-8ab991ea831 i86pc i386 i86pc

/opt/onbld/bin/i386/dmake
dmake: illumos make
number of concurrent jobs = 8

cw version 8.0
primary: /opt/gcc-10/bin/gcc
gcc (OmniOS 151046/10.4.0-il-1) 10.4.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shadow: /opt/gcc-7/bin/gcc
gcc (OmniOS 151046/7.5.0-il-2) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shadow: /data/omnios-build/omniosorg/r151046/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/smatch
0.6.1-rc1-il-7

/usr/jdk/openjdk11.0/bin/javac
openjdk full version "11.0.22+7-omnios-151046"

/usr/bin/openssl
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)

/usr/ccs/bin/ld
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1788 (illumos)

Build project:  default
Build taskid:   88

==== Nightly argument issues ====


==== Build version ====

omnios-r151046-38xx-00328dcea17

==== Make clobber ERRORS ====


==== Make tools clobber ERRORS ====


==== Bootstrap build errors ====


==== Tools build errors ====


==== Build errors (non-DEBUG) ====


==== Build warnings (non-DEBUG) ====


==== Elapsed build time (non-DEBUG) ====

real    26:16.2
user  4:01:17.3
sys   1:07:01.1

==== Build noise differences (non-DEBUG) ====


==== package build errors (non-DEBUG) ====


==== Build errors (DEBUG) ====


==== Build warnings (DEBUG) ====


==== Elapsed build time (DEBUG) ====

real    23:06.5
user  3:34:58.3
sys   1:00:58.2

==== Build noise differences (DEBUG) ====


==== package build errors (DEBUG) ====


==== Linting packages ====


==== Validating manifests against proto area ====


==== Check versioning and ABI information ====


==== Check ELF runtime attributes ====


==== Diff ELF runtime attributes (since last build) ====


==== cstyle/hdrchk errors ====


==== Find core files ====


==== Check lists of files ====


==== Impact on file permissions ====
```

**Comment by danmcd** [comment]
I'm sure @discard-this would like a hotpatch to try?

**Review by hadfl — APPROVED** [review]

**Comment by discard-this** [comment]
> I'm sure @discard-this would like a hotpatch to try?

Yep. I can test it today or next Monday-Thursday, whenever you've got something you want me to test.

nomad

**Comment by citrus-it** [comment]
> > I'm sure @discard-this would like a hotpatch to try?

There's a hotfix at https://hf.omnios.org/r46/mpt_sas.p5p should you wish to test.

**Comment by discard-this** [comment]
> There's a hotfix at https://hf.omnios.org/r46/mpt_sas.p5p should you wish to test.

I have to reconfigure the host that has the card in it (it is currently running '050 with the test HBA driver) but should be able to do some testing today.

**Comment by discard-this** [comment]
: || lvd@fs2 ~ [501] ; uname -a
SunOS fs2 5.11 omnios-r151046-8ab991ea831 i86pc i386 i86pc
(I just ran pkg update -v and rebooted.)

before applying patch:
: || lvd@fs2 ~ [502] ; iostat -En
c1t4d0           Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2KB24 Revision: 0121 Serial No: BTYS817407RE240 
Size: 240.06GB <240057409536 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c1t5d0           Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2KB24 Revision: 0121 Serial No: BTYS817409YS240 
Size: 240.06GB <240057409536 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 

after applying patch and rebooting:
: || lvd@fs2 ~ [502] ; iostat -En
c1t4d0           Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2KB24 Revision: 0121 Serial No: BTYS817407RE240 
Size: 240.06GB <240057409536 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c1t5d0           Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2KB24 Revision: 0121 Serial No: BTYS817409YS240 
Size: 240.06GB <240057409536 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C50095722E27d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E001 Serial No: ZJV0S42H0000J75 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500A612DA93d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E001 Serial No: ZJV0WCCN0000J80 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500957D2553d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E001 Serial No: ZJV0VFK30000J74 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t55CD2E414EC0FF43d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2KG48 Revision: 0121 Serial No: BTYM740600ZT480 
Size: 480.10GB <480103981056 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t55CD2E414EC0B5ABd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2KG48 Revision: 0121 Serial No: BTYM7405027L480 
Size: 480.10GB <480103981056 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500A74C4EBFd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E002 Serial No: ZJV32KQQ0000C91 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500A74AFA73d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E002 Serial No: ZJV32FC40000C91 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500A74B200Bd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E002 Serial No: ZJV32ER00000C91 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500A708D73Bd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0027    Revision: E002 Serial No: ZJV2NTRA0000C90 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t55CD2E404C20F0BFd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: ATA      Product: INTEL SSDSC2BA20 Revision: 0140 Serial No: BTHV615600VZ200 
Size: 200.05GB <200049647616 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500AF403CC7d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM0038    Revision: E002 Serial No: ZHZ5XDSN0000C02 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500C9EF0B87d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM002G    Revision: E002 Serial No: ZL21KK0H0000C95 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500C9DFFD53d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM002G    Revision: E002 Serial No: ZL24JHQC0000C02 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500D7496F73d0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM002G    Revision: E003 Serial No: ZL29FELH0000C13 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500D98E22BFd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM002G    Revision: E003 Serial No: ZTN19PGK0000C24 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 
c0t5000C500D730509Fd0 Soft Errors: 0 Hard Errors: 0 Transport Errors: 0 
Vendor: SEAGATE  Product: ST12000NM002G    Revision: E003 Serial No: ZL2HYPTH0000C14 
Size: 12000.14GB <12000138625024 bytes>
Media Error: 0 Device Not Ready: 0 No Device: 0 Recoverable: 0 
Illegal Request: 0 Predictive Failure Analysis: 0 

zpool import returned without error and zpool status shows what I expect to see.

: || lvd@fs2 ~ [504] ; zpool status pool0
  pool: pool0
 state: ONLINE
  scan: scrub repaired 0 in 0 days 00:17:47 with 0 errors on Sat Jun  1 02:00:48 2024
config:

        NAME                       STATE     READ WRITE CKSUM
        pool0                      ONLINE       0     0     0
          raidz2-0                 ONLINE       0     0     0
            c0t5000C500A612DA93d0  ONLINE       0     0     0
            c0t5000C500C9DFFD53d0  ONLINE       0     0     0
            c0t5000C50095722E27d0  ONLINE       0     0     0
            c0t5000C500AF403CC7d0  ONLINE       0     0     0
            c0t5000C500D7496F73d0  ONLINE       0     0     0
            c0t5000C500957D2553d0  ONLINE       0     0     0
          raidz2-2                 ONLINE       0     0     0
            c0t5000C500A74C4EBFd0  ONLINE       0     0     0
            c0t5000C500A74AFA73d0  ONLINE       0     0     0
            c0t5000C500A74B200Bd0  ONLINE       0     0     0
            c0t5000C500D98E22BFd0  ONLINE       0     0     0
            c0t5000C500C9EF0B87d0  ONLINE       0     0     0
            c0t5000C500A708D73Bd0  ONLINE       0     0     0
        logs    
          c0t55CD2E414EC0B5ABd0    ONLINE       0     0     0
          c0t55CD2E414EC0FF43d0    ONLINE       0     0     0
        cache
          c2t93d1                  ONLINE       0     0     0
        spares
          c2t94d1                  AVAIL   

errors: No known data errors

I've initiated a zpool scrub on the pool. What other tests would you like done at this point?

**Comment by discard-this** [comment]
: || lvd@fs2 ~ [524] ; zpool status pool0
  pool: pool0
 state: ONLINE
  scan: scrub repaired 0 in 0 days 00:17:18 with 0 errors on Wed Jun  5 15:45:26 2024

**Pull request merged**
