### PR TITLE
IPsec backports for r151022

### PR DESCRIPTION
**Pull request by danmcd**
It's a bit unusual, but I'd like these kernel changes to land in the r151022 branch.  I'm happy to take any maintenance hits if anyone uses IPsec on r151022, because I would be doing the same. I did "git cherrypick" to pull them, and merge them in properly.

### CODE REVIEW

**Comment by oetiker** [comment]
hi dan, what is the purpose of these changes ?

**Comment by hadfl** [comment]
As far as I could see, 8381 is already in bloody, the other 3 commits will land in bloody this Thursday with the weekly upstream merge.

@danmcd, are you fancy doing this week's upstream (gate and lx) merges on Thursday, as well as the backport to r22 (including these cherry-picks)?

**Comment by danmcd** [comment]
To be frank, it's mostly a shortcut for me to continue testing further IPsec development on my home server (running r151022).  You are free to reject this.

@hadfl - by gate & lx, you mean for the master branch, right?  Or are you backporting more things into the 022 branch?

**Comment by hadfl** [comment]
Yes, I mean gate & lx for master (plus selecting additional backport candidates from this week for r22, if there are any)

**Comment by oetiker** [comment]
merging is fine with me

**Comment by danmcd** [comment]
Am I still on the hook for the other stuff?  The LX state is now elsewhere... I'd be happy to get master up to date with -gate, however.

**Comment by citrus-it** [comment]
Yes, let's keep with the process we have so far. Do the next weekly upstream merge on Thursday (including build and onu test) and select these for backport after that.

**Comment by danmcd** [comment]
Please indicate when processes have completed and I'll merge/re-merge this.

**Comment by citrus-it** [comment]
Hi Dan,

The process that we've adopted so far is (emergencies aside) to merge with upstream weekly on a Thursday. We pull both upstream_gate and upstream_joyent at the same time so that they're in-sync, but merge the gate changes first, do a nightly and onu to test. This then becomes a pull request in which people vote. 

Once the gate changes are merged, then the Joyent commits are cherry picked using a very similar process to the one you developed. Again we do a full nightly and onu before raising a PR for voting.

After that, we decide on what is to be back-ported to stable and whether they will trigger a weekly release on the Monday. The backported changes become yet another PR which is voted on. Writing it out now it appears more onerous than it actually is!

The process is documented so far at https://github.com/omniosorg/omnios-build/blob/master/doc/sync-upstream.md

I don't think that any of the changes you've included in this request would have naturally found their way into the backport list so your guidance is appreciated here.

@hadfl has the task of doing this week's upstream merges and backports starting on Thursday. Above, I think he was asking if you want to take on those tasks this week using our documented process.
It might be a bit early since it's only our third week and we're still working some things out there but if you're up for it I'm sure he would work through it with you and it would probably show up some places where the documentation could be improved. 

Otherwise expect these requested changes to be merged into the r22 branch sometime over the weekend. We are unlikely to do an update on the IPS repository for these if a reboot is required (apologies that I haven't checked as I only have intermittent access this week) but we could make a .p5p archive available for download containing the updated packages if you want it, although I imagine you may just build your own!

**Comment by danmcd** [comment]
I just want to, in the long-term, not constantly be running ONU'ed bits.  I understand they won't percolate out to the r151022 repo server until you all are willing to issue an 022 update that requires a reboot, as well.

It's all good.  Just pull, or have me push, this in at your convenience, and tell me a rough ETA for when it lands in the actual r151022 repo.

**Pull request merged**
