### PR TITLE
LX: isatty() should return ENOTTY if not a TTY (r151034)

### PR DESCRIPTION
**Pull request by citrus-it**

### CODE REVIEW

**Comment by danmcd** [comment]
Per conversation with Zeller/papertigers, is there a test program one can easily run to confirm this?

**Comment by citrus-it** [comment]
> Per conversation with Zeller/papertigers, is there a test program one can easily run to confirm this?

As far as I know, it's easily seen with the omnios lx ubuntu image where systemd fails to start services with 'Failed to change ownership of terminal'

Alternatively, Tobi has been using the following perl script:

```
# perl -E 'use POSIX qw(errno isatty); open my $fh,"/dev/null"; my $fn = fileno($fh);  print isatty($fn);say errno,": ",$!'
25: Inappropriate ioctl for device
```

**Comment by oetiker** [comment]
I fixed the `user@.service` with a special override in the lx image ... but if you use any other service which tries to set the owner of the process then it fails ...

but the perl script is the most straight forward test

**Comment by oetiker** [comment]
it seems that systemd.user in ubuntu 20.04 checks the errno after a failed call to iastty ...

**Comment by papertigers** [comment]
This seems okay to me.

**Pull request merged**
