### PR TITLE
Merge network overlay devices from upstream illumos-joyent

### PR DESCRIPTION
**Pull request by citrus-it**
## onu

```
bloody% uname -a
SunOS bloody 5.11 omnios-overlay-09cd44c17f i86pc i386 i86pc
```
## mail_msg

```

==== Nightly distributed build started:   Thu Feb 27 11:53:48 UTC 2020 ====
==== Nightly distributed build completed: Thu Feb 27 13:01:10 UTC 2020 ====

==== Total build time ====

real    1:07:22

==== Build environment ====

/usr/bin/uname
SunOS bloody 5.11 omnios-master-06862facb5 i86pc i386 i86pc

/opt/onbld/bin/i386/dmake
dmake: illumos make
number of concurrent jobs = 8

cw version 5.0
primary: /opt/gcc-7/bin/gcc
gcc (OmniOS 151033/7.5.0-il-1) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shadow: /opt/gcc-4.4.4/bin/gcc
gcc (GCC) 4.4.4
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shadow: /data/omnios-build/omniosorg/bloody/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/smatch
0.6.1-rc1-il-4

/usr/jdk/openjdk1.8.0/bin/javac
openjdk full version "1.8.0_242-omnios-151033-b07"

/usr/bin/openssl
OpenSSL 1.1.1d  10 Sep 2019
    API_COMPAT=0x10000000L

/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009

/usr/ccs/bin/ld
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1763 (illumos)

Build project:  default
Build taskid:   131

==== Nightly argument issues ====


==== Build version ====

omnios-overlay-09cd44c17f

==== Make clobber ERRORS ====


==== Make tools clobber ERRORS ====


==== Bootstrap build errors ====


==== Tools build errors ====


==== Build errors (non-DEBUG) ====


==== Build warnings (non-DEBUG) ====


==== Elapsed build time (non-DEBUG) ====

real    26:50.6
user  3:45:15.3
sys     58:42.4

==== Build noise differences (non-DEBUG) ====


==== package build errors (non-DEBUG) ====


==== Build errors (DEBUG) ====


==== Build warnings (DEBUG) ====


==== Elapsed build time (DEBUG) ====

real    24:03.5
user  3:21:07.1
sys     54:31.5

==== Build noise differences (DEBUG) ====


==== package build errors (DEBUG) ====


==== Validating manifests against proto area ====


==== Check versioning and ABI information ====


==== Check ELF runtime attributes ====


==== Diff ELF runtime attributes (since last build) ====


==== cstyle/hdrchk errors ====


==== Find core files ====


==== Check lists of files ====


==== Impact on file permissions ====
```

### CODE REVIEW

**Comment by citrus-it** [comment]
> that looks extreemely fancy ... is this following some standard, or are these overlay neworks something which will work between smartos and omnios hosts for now ?

VXLAN encapsulation is a standard so there is no reason that this should not interoperate with other implementations (VMware NSX for example); it just hasn't been tested.

**Comment by danmcd** [comment]
The encapsulation IS interoperable, but the MAC to underlay IP mapping (SVP) isn't.  Are you bringing along portolan or some other SVP server as part of this?  Or are you introducing an alternate resolution or mapping?

I'd advise against bringing in overlay/underlay until you've worked out these things.  They're great when you control the whole cloud ecosystem, but as of now OmniOS isn't part of a self-contained ecosystem, it must be interoperable.

**Comment by danmcd** [comment]
SVP SmartDC Vxlan Protocol

Portolan is an implementation of an SVP server.

**Comment by citrus-it** [comment]
> The encapsulation IS interoperable, but the MAC to underlay IP mapping (SVP) isn't. Are you bringing along portolan or some other SVP server as part of this? Or are you introducing an alternate resolution or mapping?
> 
> I'd advise against bringing in overlay/underlay until you've worked out these things. They're great when you control the whole cloud ecosystem, but as of now OmniOS isn't part of a self-contained ecosystem, it must be interoperable.

We're bringing in the `direct` and `files` search plugins and they have been working well in testing. SVP is not part of this wad.

**Comment by danmcd** [comment]
Sorry for forgetting about the direct and files plugins.

Some vxlan implementations implement link-layer broadcast & multicast by mapping them to a single mcast group for the vxlanid, and tricking the upper layer IP into thinking it's a regular ethernet-like card.  It's been a while since I dug down there, but I can't recall if the existing plugin architecture makes that easy or not.  There are concerns that switches used for an underlay can't cope with too much multicast (a public cloud could easily fill a good portion of the 16M VXLAN IDs).

**Comment by citrus-it** [comment]
> Sorry for forgetting about the direct and files plugins.

The comment about interoperability was a bit misleading. We're bringing this into OmniOS to allow people to spread one or more L2 domains across two or more **OmniOS servers**. The direct plugin allows this easily across two servers, files across more (with the overhead of maintaining the L2 routing information across the domain). SVP is on the radar for a possible future integration but may never happen.

I'm familiar with the various options offered by other implementations (in particular VMware) in terms of L2 or L3 multicast for broadcast, unknown unicast and multicast packets on the virtual switch, but that's out of scope here.
I mentioned VMware as a potential future interop as it does support what is effectively direct mode with third party VXLAN gateways; I just have no idea if it would work with OmniOS (but I should get a chance to trial it in the next 6 months or so).

**Pull request merged**
