### PR TITLE
5709 Add binary compatibility with Solaris 10 update 10.

### PR DESCRIPTION
**Pull request by mvwieringen**
Reviewed by: Peter Tribble <peter.tribble@gmail.com>
Reviewed by: Igor Kozhukhov <igor@dilos.org>
Reviewed by: Garrett D'Amore <garrett@damore.org>

### CODE REVIEW

**Comment by citrus-it** [comment]
To be clear - I am currently undecided about whether the OI approach is preferable but am leaning towards it. Let's see what other reviewers think.

**Comment by mvwieringen** [comment]
Ok clear honestly I think this approach is cleaner but leave it to others to decide what road to take.
In the end as long as the symbols are available is what I want to achieve. I also think the issue you raise about newer binaries not running on older releases is also how normally binary compatibility (e.g. ABI stability) works so I don't see that as a disadvantage.

**Comment by mvwieringen** [comment]
Ok I have cherry picked the change from openindiana so if people like me to I can push this branch and update this PR.

**Comment by oetiker** [comment]
@mvwieringen I guess the problem with moving the symbols would make them disappear for some binaries that are using them now (as they got discovered via configure) ... but I don't really have a clue how this works in omnios, so maybe I am thinking too simple here.

**Comment by oetiker** [comment]
so there seem to be no downside to the OI approach then

**Comment by citrus-it** [comment]
@mvwieringen - yes please, can you update the PR with the patch that just adds the new version with a dummy symbol?

**Comment by mvwieringen** [comment]
Done

**Comment by citrus-it** [comment]
And there is a simple test case at https://downloads.omniosce.org/misc/c_1.22.7

```
% ./c_1.22.7
ld.so.1: c_1.22.7: fatal: libc.so.1: version 'SUNW_1.22.7' not found (required by file c_1.22.7)
ld.so.1: c_1.22.7: fatal: libc.so.1: open failed: No such file or directory
```

**Pull request merged**
