### PR TITLE
Upstream merge/2017070301

### PR DESCRIPTION
**Pull request by citrus-it**
Backport candidates:

* 8378 crash due to bp in-memory modification of nopwrite block
* 8377 Panic in bookmark deletion  …
* 3167 kernel panic in apix:apic_timer_init
* 7600 zfs rollback should pass target snapshot to kernel
* 8438 panic in vnode_valid_pn

### CODE REVIEW

**Comment by danmcd** [comment]
What does mail_msg look like?

**Comment by citrus-it** [comment]
Hmm.. not too good actually. I need to add a nightly build to the notes.

```
==== Nightly distributed build started:   Tue Jul  4 13:27:59 UTC 2017 ====
==== Nightly distributed build completed: Tue Jul  4 14:07:16 UTC 2017 ====

==== Total build time ====

real    0:39:17

==== Build environment ====

/usr/bin/uname
SunOS build 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc

/opt/onbld/bin/i386/dmake
dmake: illumos make
number of concurrent jobs = 4

32-bit compiler
/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE DISABLED)
primary: /opt/gcc-4.4.4//bin/gcc
gcc (GCC) 4.4.4

64-bit compiler
/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE DISABLED)
primary: /opt/gcc-4.4.4//bin/gcc
gcc (GCC) 4.4.4

/usr/java/bin/javac
openjdk full version "1.7.0_101-b00"

/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009

/usr/ccs/bin/ld
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1755 (illumos)

Build project:  default
Build taskid:   649581

==== Nightly argument issues ====


==== Build version ====

omnios- upstream-merge/2017070301-8a5908ecf9

==== Make clobber ERRORS ====


==== Make tools clobber ERRORS ====


==== Tools build errors ====


==== Build errors (DEBUG) ====

dmake: Warning: Target `install.targ' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `privcmd'
dmake: Warning: Target `install.targ' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `xnf'
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `i86xpv'
dmake: Warning: Target `install.targ' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `ppm'
dmake: Warning: Target `install.targ' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `xdf'
dmake: Warning: Target `install' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `i86pc'
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `uts'
The following command caused the error:
dmake: Warning: Target `all' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `Adm'
dmake: Warning: Target `install' not remade because of errors
The following command caused the error:
dmake: Warning: Target `install' not remade because of errors

==== Build warnings (DEBUG) ====

dmake: Warning: Target `install.targ' not remade because of errors
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `privcmd'
dmake: Warning: Target `install.targ' not remade because of errors
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `xnf'
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `i86xpv'
dmake: Warning: Target `install.targ' not remade because of errors
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `ppm'
dmake: Warning: Target `install.targ' not remade because of errors
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `xdf'
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `i86pc'
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `uts'
dmake: Warning: Target `all' not remade because of errors
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Command failed for target `Adm'
dmake: Warning: Target `install' not remade because of errors
dmake: Warning: Target `install' not remade because of errors

==== Elapsed build time (DEBUG) ====

real    16:54.8
user  1:34:22.8
sys     11:05.1

==== Build noise differences (DEBUG) ====

50a51
> ERROR: ctfmerge: ../../../intel/genunix/debug32/genunix: Unexpected end of function symbols
84c85
< dmake: Warning: Command failed for target `domcaps'
---
> dmake: Warning: Command failed for target `i86pc'
85a87
> dmake: Warning: Command failed for target `ppm'
87a90
> dmake: Warning: Command failed for target `xdf'

==== 'dmake lint' of src ERRORS ====


==== Elapsed time of 'dmake lint' of src ====

real    19:07.8
user  1:07:42.2
sys     20:11.6

==== lint warnings src ====

"/data/omnios-build/omniosorg/illumos-omnios/usr/src/uts/common/io/iwn/if_iwn.c", line 2052: warning: function returns value which is sometimes ignored: memset (E_FUNC_RET_MAYBE_IGNORED2)
"/data/omnios-build/omniosorg/illumos-omnios/usr/src/uts/common/os/sysent.c", line 1213: warning: function returns value which is always ignored: yield (E_FUNC_RET_ALWAYS_IGNOR2)

==== lint noise differences src ====


==== cstyle/hdrchk errors ====

dmake: Warning: Command failed for target `lx.5.check'
dmake: Warning: Command failed for target `man'
dmake: Warning: Command failed for target `man5'
dmake: Warning: Command failed for target `man7d'
dmake: Warning: Command failed for target `zfd.7d.check'
dmake: Warning: Target `check' not remade because of errors
mandoc: lx.5:124:57: WARNING: new sentence, new line
mandoc: lx.5:130:49: WARNING: new sentence, new line
mandoc: lx.5:132:7: WARNING: new sentence, new line
mandoc: lx.5:139:70: WARNING: new sentence, new line
mandoc: lx.5:28:14: WARNING: new sentence, new line
mandoc: lx.5:29:20: WARNING: new sentence, new line
mandoc: lx.5:29:71: WARNING: new sentence, new line
mandoc: lx.5:43:26: WARNING: new sentence, new line
mandoc: lx.5:67:12: WARNING: new sentence, new line
mandoc: lx.5:72:32: WARNING: new sentence, new line
mandoc: lx.5:81:74: WARNING: new sentence, new line
mandoc: lx.5:88:50: WARNING: new sentence, new line
mandoc: zfd.7d:41:62: WARNING: new sentence, new line
mandoc: zfd.7d:64:61: WARNING: new sentence, new line
mandoc: zfd.7d:70:7: WARNING: new sentence, new line
mandoc: zfd.7d:73:35: WARNING: new sentence, new line
mandoc: zfd.7d:74:38: WARNING: new sentence, new line

==== Find core files ====


==== Check lists of files ====
```

**Comment by danmcd** [comment]
Clearly you merged something wrong.  The lint errors and man page ones, however, are inherited because of OmniOS's slightly-newer version of lint.  (Upstream uses lint from the same path as the Studio compilers, which is not correct.)

I was occasionally merging and upstreaming to the parent OmniOS repo (to which I can still push).  Would you all like me to do it again?

**Comment by hadfl** [comment]
i guess "hand-holding" from your side at this early stage is highly appreciated by all :)

**Comment by citrus-it** [comment]
I appreciate the offer but from what's been discussed on gitter we want to handle upstream merges through PRs so that we get a chance to review the changes for backporting.

**Comment by citrus-it** [comment]
Ok, I now have a clean build of this branch - the problem was with the way that the branch name was being extracted in the .env file (originally taken from /opt/onbld) to construct the release name.

```
==== Nightly distributed build started:   Tue Jul  4 20:54:38 UTC 2017 ====
==== Nightly distributed build completed: Tue Jul  4 21:31:41 UTC 2017 ====

==== Total build time ====

real    0:37:03

==== Build environment ====

/usr/bin/uname
SunOS build 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc

/opt/onbld/bin/i386/dmake
dmake: illumos make
number of concurrent jobs = 8

32-bit compiler
/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE DISABLED)
primary: /opt/gcc-4.4.4//bin/gcc
gcc (GCC) 4.4.4

64-bit compiler
/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE DISABLED)
primary: /opt/gcc-4.4.4//bin/gcc
gcc (GCC) 4.4.4

/usr/java/bin/javac
openjdk full version "1.7.0_101-b00"

/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009

/usr/ccs/bin/ld
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1755 (illumos)

Build project:  default
Build taskid:   655789

==== Nightly argument issues ====


==== Build version ====

omnios-upstream-merge-2017070301-8a5908ecf9

==== Make clobber ERRORS ====


==== Make tools clobber ERRORS ====


==== Tools build errors ====


==== Build errors (DEBUG) ====


==== Build warnings (DEBUG) ====


==== Elapsed build time (DEBUG) ====

real    12:32.3
user  1:49:40.6
sys     15:54.8

==== Build noise differences (DEBUG) ====

87,88c83,84
< maximum offset: 1d50
< maximum offset: 23ac
---
> maximum offset: 1d4d
> maximum offset: 23a9

==== package build errors (DEBUG) ====


==== Validating manifests against proto area ====


==== Check versioning and ABI information ====


==== Check ELF runtime attributes ====


==== Diff ELF runtime attributes (since last build) ====

6668a6669
> lib/amd64/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_channel_program
6682a6684
> lib/amd64/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_rollback_to
14129a14132
> lib/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_channel_program
14143a14147
> lib/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_rollback_to
14444a14449,14451
> opt/zfs-tests/tests/functional/channel_program/lua_core/nvlist_to_lua.exe: NEEDED=libc.so.1
> opt/zfs-tests/tests/functional/channel_program/lua_core/nvlist_to_lua.exe: NEEDED=libnvpair.so.1
> opt/zfs-tests/tests/functional/channel_program/lua_core/nvlist_to_lua.exe: NEEDED=libzfs_core.so.1
20411d20417
< usr/lib/calprog: NEEDED=libc.so.1
30433a30440,30441
> usr/sbin/nvmeadm: NEEDED=libc.so.1
> usr/sbin/nvmeadm: NEEDED=libdevinfo.so.1

==== 'dmake lint' of src ERRORS ====


==== Elapsed time of 'dmake lint' of src ====

real    17:50.8
user  1:33:09.8
sys     42:52.7

==== lint warnings src ====

"/data/omnios-build/omniosorg/illumos-omnios/usr/src/uts/common/io/iwn/if_iwn.c", line 2052: warning: function returns value which is sometimes ignored: memset (E_FUNC_RET_MAYBE_IGNORED2)
"/data/omnios-build/omniosorg/illumos-omnios/usr/src/uts/common/os/sysent.c", line 1213: warning: function returns value which is always ignored: yield (E_FUNC_RET_ALWAYS_IGNOR2)

==== lint noise differences src ====


==== cstyle/hdrchk errors ====

dmake: Warning: Command failed for target `lx.5.check'
dmake: Warning: Command failed for target `man'
dmake: Warning: Command failed for target `man5'
dmake: Warning: Command failed for target `man7d'
dmake: Warning: Command failed for target `zfd.7d.check'
dmake: Warning: Target `check' not remade because of errors
mandoc: lx.5:124:57: WARNING: new sentence, new line
mandoc: lx.5:130:49: WARNING: new sentence, new line
mandoc: lx.5:132:7: WARNING: new sentence, new line
mandoc: lx.5:139:70: WARNING: new sentence, new line
mandoc: lx.5:28:14: WARNING: new sentence, new line
mandoc: lx.5:29:20: WARNING: new sentence, new line
mandoc: lx.5:29:71: WARNING: new sentence, new line
mandoc: lx.5:43:26: WARNING: new sentence, new line
mandoc: lx.5:67:12: WARNING: new sentence, new line
mandoc: lx.5:72:32: WARNING: new sentence, new line
mandoc: lx.5:81:74: WARNING: new sentence, new line
mandoc: lx.5:88:50: WARNING: new sentence, new line
mandoc: zfd.7d:41:62: WARNING: new sentence, new line
mandoc: zfd.7d:64:61: WARNING: new sentence, new line
mandoc: zfd.7d:70:7: WARNING: new sentence, new line
mandoc: zfd.7d:73:35: WARNING: new sentence, new line
mandoc: zfd.7d:74:38: WARNING: new sentence, new line

==== Find core files ====


==== Check lists of files ====


==== Impact on file permissions ====
```

**Comment by hadfl** [comment]
booted sucessfully into it:
```
hadfl@mars:~$ beadm list
BE                  Active Mountpoint Space Policy Created
omnios              -      -          33.1M static 2017-07-05 03:07
upstream-2017070301 NR     /          7.29G static 2017-07-05 13:46
hadfl@mars:~$ uname -a
SunOS mars 5.11 omnios-upstream-merge-2017070301-8a5908ecf9 i86pc i386 i86pc
```

mail_msg:
```
==== Nightly distributed build started:   Wed Jul  5 12:41:17 CEST 2017 ====
==== Nightly distributed build completed: Wed Jul  5 13:37:46 CEST 2017 ====

==== Total build time ====

real    0:56:29

==== Build environment ====

/usr/bin/uname
SunOS mars 5.11 omnios-master-8b31933c62 i86pc i386 i86pc

/opt/onbld/bin/i386/dmake
dmake: illumos make
number of concurrent jobs = 8

32-bit compiler
/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE DISABLED)
primary: /opt/gcc-4.4.4//bin/gcc
gcc (GCC) 4.4.4

64-bit compiler
/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE DISABLED)
primary: /opt/gcc-4.4.4//bin/gcc
gcc (GCC) 4.4.4

/usr/java/bin/javac
openjdk full version "1.7.0_101-b00"

/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009

/usr/ccs/bin/ld
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1755 (illumos)

Build project:  default
Build taskid:   75

==== Nightly argument issues ====


==== Build version ====

omnios-upstream-merge-2017070301-8a5908ecf9

==== Make clobber ERRORS ====


==== Make tools clobber ERRORS ====


==== Tools build errors ====


==== Build errors (non-DEBUG) ====


==== Build warnings (non-DEBUG) ====


==== Elapsed build time (non-DEBUG) ====

real    17:43.1
user  1:06:34.7
sys      5:01.3

==== Build noise differences (non-DEBUG) ====


==== package build errors (non-DEBUG) ====


==== Build errors (DEBUG) ====


==== Build warnings (DEBUG) ====


==== Elapsed build time (DEBUG) ====

real    14:56.1
user    59:02.5
sys      3:29.7

==== Build noise differences (DEBUG) ====

1d0
< 	-classpath /export/home/hadfl/build/illumos-omnios/usr/src/lib/libdtrace_jni/java/classes:/export/home/hadfl/build/illumos-omnios/usr/src/lib/libdtrace_jni/java/src -d /export/home/hadfl/build/illumos-omnios/proto/root_i386/usr/share/lib/java/javadoc/dtrace/api \
6d4
< 	print "export PATH=/usr/ast/bin:/usr/xpg6/bin:/usr/xpg4/bin:/usr/bin:\${PATH}" ; \
46,48d43
< : libcommon.a
< : libdrivers.a
< : libgrub.a
51,80d45
< Note: /export/home/hadfl/build/illumos-omnios/usr/src/cmd/pools/poold/com/sun/solaris/domain/pools/ResourceMonitor.java uses unchecked or unsafe operations.
< Note: /export/home/hadfl/build/illumos-omnios/usr/src/cmd/print/printmgr/com/sun/admin/pm/server/Debug.java uses unchecked or unsafe operations.
< Note: BST.java uses unchecked or unsafe operations.
< Note: Configuration.java uses unchecked or unsafe operations.
< Note: Debug.java uses unchecked or unsafe operations.
< Note: DecisionHistory.java uses unchecked or unsafe operations.
< Note: Element.java uses unchecked or unsafe operations.
< Note: LocalityGroup.java uses unchecked or unsafe operations.
< Note: Move.java uses unchecked or unsafe operations.
< Note: Pool.java uses unchecked or unsafe operations.
< Note: Recompile with -Xlint:unchecked for details.
< Note: Resource.java uses unchecked or unsafe operations.
< Note: ResourceMonitor.java uses unchecked or unsafe operations.
< Note: Severity.java uses unchecked or unsafe operations.
< Note: Some input files use unchecked or unsafe operations.
< Note: StatisticList.java uses unchecked or unsafe operations.
< Note: SysloglikeFormatter.java uses unchecked or unsafe operations.
< Note: SystemMonitor.java uses unchecked or unsafe operations.
< Note: SystemSolver.java uses unchecked or unsafe operations.
< Note: helptools/parseMain.java uses unchecked or unsafe operations.
< Note: pmButton.java uses unchecked or unsafe operations.
< Note: pmHelpDetailPanel.java uses unchecked or unsafe operations.
< Note: pmHelpIndexPanel.java uses unchecked or unsafe operations.
< Note: pmHelpRepository.java uses unchecked or unsafe operations.
< Note: pmHelpSearchPanel.java uses unchecked or unsafe operations.
< Note: pmInstallPrinter.java uses unchecked or unsafe operations.
< Note: pmInstallScreen.java uses unchecked or unsafe operations.
< Note: pmLoad.java uses unchecked or unsafe operations.
< Note: pmMessageDialog.java uses unchecked or unsafe operations.
< Note: pmTop.java uses unchecked or unsafe operations.
83,84c48,49
< maximum offset: 1d3f
< maximum offset: 239b
---
> maximum offset: 1d52
> maximum offset: 23ae
87,90d51
< sed 's/.c:#define/,/'                   |\
< sed -e '/^.include/s:\.\..*/rpcsvc:rpcsvc:' < nlm_prot_xdr.c.tmp > nlm_prot_xdr.c
< sed -e '/^.include/s:\.\..*/rpcsvc:rpcsvc:' < nsm_addr_xdr.c.tmp > nsm_addr_xdr.c
< sed -e '/^.include/s:\.\..*/rpcsvc:rpcsvc:' < sm_inter_xdr.c.tmp > sm_inter_xdr.c

==== package build errors (DEBUG) ====


==== Validating manifests against proto area ====


==== Check versioning and ABI information ====


==== Check ELF runtime attributes ====


==== Diff ELF runtime attributes (since last build) ====

6668a6669
> lib/amd64/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_channel_program
6682a6684
> lib/amd64/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_rollback_to
14129a14132
> lib/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_channel_program
14143a14147
> lib/libzfs_core.so.1: VERSION=ILLUMOS_0.1, SYMBOL=lzc_rollback_to
14444a14449,14451
> opt/zfs-tests/tests/functional/channel_program/lua_core/nvlist_to_lua.exe: NEEDED=libc.so.1
> opt/zfs-tests/tests/functional/channel_program/lua_core/nvlist_to_lua.exe: NEEDED=libnvpair.so.1
> opt/zfs-tests/tests/functional/channel_program/lua_core/nvlist_to_lua.exe: NEEDED=libzfs_core.so.1
20411d20417
< usr/lib/calprog: NEEDED=libc.so.1
30433a30440,30441
> usr/sbin/nvmeadm: NEEDED=libc.so.1
> usr/sbin/nvmeadm: NEEDED=libdevinfo.so.1

==== 'dmake lint' of src ERRORS ====


==== Elapsed time of 'dmake lint' of src ====

real    18:02.6
user    45:31.3
sys      4:38.2

==== lint warnings src ====

"/export/home/hadfl/build/illumos-omnios/usr/src/uts/common/io/iwn/if_iwn.c", line 2052: warning: function returns value which is sometimes ignored: memset (E_FUNC_RET_MAYBE_IGNORED2)
"/export/home/hadfl/build/illumos-omnios/usr/src/uts/common/os/sysent.c", line 1213: warning: function returns value which is always ignored: yield (E_FUNC_RET_ALWAYS_IGNOR2)

==== lint noise differences src ====

2a3,4
> PROGS: cleanup setup tst.args_to_lua tst.divide_by_zero tst.integer_illegal tst.integer_overflow tst.language_functions_neg tst.language_functions_pos tst.large_prog tst.memory_limit tst.nested_neg tst.nested_pos tst.nvlist_to_lua tst.recursive_neg tst.recursive_pos tst.return_nvlist_neg tst.return_nvlist_pos tst.return_recursive_table tst.timeout nvlist_to_lua.exe
> SRCS: nvlist_to_lua.c
7a10,11
> echo PROGS: cleanup setup tst.args_to_lua tst.divide_by_zero tst.integer_illegal tst.integer_overflow tst.language_functions_neg tst.language_functions_pos tst.large_prog tst.memory_limit tst.nested_neg tst.nested_pos tst.nvlist_to_lua tst.recursive_neg tst.recursive_pos tst.return_nvlist_neg tst.return_nvlist_pos tst.return_recursive_table tst.timeout nvlist_to_lua.exe
> echo SRCS: nvlist_to_lua.c

==== cstyle/hdrchk errors ====

dmake: Warning: Command failed for target `lx.5.check'
dmake: Warning: Command failed for target `man'
dmake: Warning: Command failed for target `man5'
dmake: Warning: Command failed for target `man7d'
dmake: Warning: Command failed for target `zfd.7d.check'
dmake: Warning: Target `check' not remade because of errors
mandoc: lx.5:124:57: WARNING: new sentence, new line
mandoc: lx.5:130:49: WARNING: new sentence, new line
mandoc: lx.5:132:7: WARNING: new sentence, new line
mandoc: lx.5:139:70: WARNING: new sentence, new line
mandoc: lx.5:28:14: WARNING: new sentence, new line
mandoc: lx.5:29:20: WARNING: new sentence, new line
mandoc: lx.5:29:71: WARNING: new sentence, new line
mandoc: lx.5:43:26: WARNING: new sentence, new line
mandoc: lx.5:67:12: WARNING: new sentence, new line
mandoc: lx.5:72:32: WARNING: new sentence, new line
mandoc: lx.5:81:74: WARNING: new sentence, new line
mandoc: lx.5:88:50: WARNING: new sentence, new line
mandoc: zfd.7d:41:62: WARNING: new sentence, new line
mandoc: zfd.7d:64:61: WARNING: new sentence, new line
mandoc: zfd.7d:70:7: WARNING: new sentence, new line
mandoc: zfd.7d:73:35: WARNING: new sentence, new line
mandoc: zfd.7d:74:38: WARNING: new sentence, new line

==== Find core files ====


==== Check lists of files ====


==== Impact on file permissions ====
```

**Comment by citrus-it** [comment]
Nice, thanks. I was going to wait for Dan to cast his eye over the mail_msg since he has experience with this but as you've managed to replicate the build and boot into it, I'll push it.
(Two approvals and over 2 days)

**Pull request merged**
