### PR TITLE
Backports to r151038

### PR DESCRIPTION
**Pull request by citrus-it**
### ONU
```
OmniOS r151038  omnios-bpr38-a1d9df9cce July 2021
illumos development build: 2021-Jul-02 [illumos]
You have new mail.
r151038% uname -a
SunOS r151038 5.11 omnios-bpr38-a1d9df9cce i86pc i386 i86pc
```

## mail_msg

```

==== Nightly distributed build started:   Fri Jul  2 21:24:01 UTC 2021 ====
==== Nightly distributed build completed: Fri Jul  2 22:53:12 UTC 2021 ====

==== Total build time ====

real    1:29:11

==== Build environment ====

/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-685fb14e78 i86pc i386 i86pc

/opt/onbld/bin/i386/dmake
dmake: illumos make
number of concurrent jobs = 8

cw version 5.0
primary: /opt/gcc-7/bin/gcc
gcc (OmniOS 151038/7.5.0-il-1) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shadow: /opt/gcc-4.4.4/bin/gcc
gcc (GCC) 4.4.4
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shadow: /data/omnios-build/omniosorg/r151038/illumos/usr/src/tools/proto/root_i
386-nd/opt/onbld/bin/i386/smatch
0.6.1-rc1-il-5

/usr/jdk/openjdk11.0/bin/javac
openjdk full version "11.0.11+9-omnios-151038"

/usr/bin/openssl
OpenSSL 1.1.1k  25 Mar 2021
    API_COMPAT=0x10000000L

/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009

/usr/ccs/bin/ld
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1765 (illumos)

Build project:  default
Build taskid:   154

==== Nightly argument issues ====


==== Build version ====

omnios-bpr38-a1d9df9cce

==== Make clobber ERRORS ====


==== Make tools clobber ERRORS ====


==== Bootstrap build errors ====


==== Tools build errors ====


==== Build errors (non-DEBUG) ====


==== Build warnings (non-DEBUG) ====


==== Elapsed build time (non-DEBUG) ====

real    34:47.6
user  5:22:10.8
sys   1:34:13.0

==== Build noise differences (non-DEBUG) ====


==== package build errors (non-DEBUG) ====


==== Build errors (DEBUG) ====


==== Build warnings (DEBUG) ====


==== Elapsed build time (DEBUG) ====

real    30:38.4
user  4:41:05.6
sys   1:25:36.0

==== Build noise differences (DEBUG) ====


==== package build errors (DEBUG) ====


==== Validating manifests against proto area ====


==== Check versioning and ABI information ====


==== Check ELF runtime attributes ====


==== Diff ELF runtime attributes (since last build) ====


==== cstyle/hdrchk errors ====


==== Find core files ====


==== Check lists of files ====


==== Impact on file permissions ====


==== Linting packages ====
```

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
This looks like a straight-up cherrypick of 13902 & 13915.  You will also need to modify usr/src/uts/common/brand/lx/os/lx_misc.c as it ALSO calls installctx().

**Comment by danmcd** [comment]
And you obviously already know about virtualbox! :)

**Comment by citrus-it** [comment]
> This looks like a straight-up cherrypick of 13902 & 13915. You will also need to modify usr/src/uts/common/brand/lx/os/lx_misc.c as it ALSO calls installctx().

The lx change is in here as a separate commit, and I just updated the mail_msg following a successful build of these bits. It's very possible I hadn't pushed the final branch when you commented, github seems to put things in its own order sometimes.

**Review by danmcd — APPROVED** [review]
Github must've been acting up.

**Review by hadfl — APPROVED** [review]

**Pull request merged**
